### ISSUE TITLE
ServiceMonitor: simplify installation of recording nodes.

### ISSUE THREAD

**Issue by PrevasNisse** [PrevasAutArch/AutArchCustomer#8]
Streamline the notion of 'Responsible' and 'OPCDAClientName'.
It should be clear which parts of which configs that are used in the installation of UA.

**Comment by LinusEvertsson** [comment]
- Tooltips have been added to all proprties in configuration dialog.
- Renamed a Admin column from "Client name" to "Client name/Responsible" and added a tooltip to the column.
- Extra configs (currently only for OPCUA adapter) is opened automatically when installing a new service.
